### PR TITLE
Added support for ESP32/ESP8266/Arduino and Rotary Encoder.

### PR DESCRIPTION
**Pull request by yhfudev**
Added following features:

* Arduino
* ESP32/ESP8266
* TFT eSPI library
* Adafruit GFX libraries
* Rotary Encoder
* Some rotary demo from other project.

So this project will be a complete start project for embedded systems.

### CODE REVIEW

**Comment by puzrin** [comment]
I don't like idea to put here everything user can imagine. Especially, until win sdl2 support done.

This will increase maintenance cost significantly, without adding a lot of value. IMO, with current limited support, it's better to focus on more generic things:

- show how to make config for PC & hardware, to develop code fast, and unify peripheral via hal.
- make pc suport (emulator) cross platform (currently should work with linux/osx only)

**Comment by kisvegabor** [comment]
@yhfudev Could you add these features to `lv_drivers` repo?

**Comment by yhfudev** [comment]
@kisvegabor, @puzrin 

The features here may not compatible with the lv_drivers.
The demo code depends on various libraries, and it is simplified for the application layer code.
The initialization code of the LCD driver need to be adjusted for different HWs, such as pins, address etc. So the user need to either specify the parameters in their main code (such as Adafruit), or setup config in header file(such as TFT eSPI). In lv_drivers, there're a lot of parameters in lv_drv_conf.h, and it not easy to be adapted to above lib to simplify the usage.

Anyway, lvgl is a great project for a embedded system which need moderate GUI widgets, due to its simple interface for LCD and inputs. I would suggest that you add demo features for ESP/Arduino framework. And for the lvgl, I would recommend to try to support other low level GFX lib, instead of supporting HWs directly.

**Comment by puzrin** [comment]
IMO, due lack of human resources, i would stay with PIO-specific features only. That's valuable. Adding more libs is NOT PIO-specific task.

Also, if anyone with to maintain more PIO samples - this can be done in separate repo. If it survives, we can merge repos to winner later.

**Comment by embeddedt** [comment]
> And for the lvgl, I would recommend to try to support other low level GFX lib, instead of supporting HWs directly.

The frequent issue with "stacking" libraries that I usually see is performance. Do the other low-level libraries you have in mind support efficient blitting of a bitmap to a specified region of the display?

This could still be useful as a fast way to get started. Nevertheless, I often find reimplementing the driver for LittlevGL itself to be quicker.

**Comment by kisvegabor** [comment]
Supporting existing libs would make really porting of lvgl much easier but I'm also concerned about the performance (as @embeddedt  pointed out)

@yhfudev Can you suggest a driver pack where there is API for an effective blit (copy image to a region) function?

**Comment by puzrin** [comment]
Closing as "too much". Let's keep this repo simple, with pio-specific things only.

**Comment by yhfudev** [comment]
What's the expect performance you want of a low level gfx driver?

**Pull request closed without merging**
