### PR TITLE
Added support for Mac OSX

### PR DESCRIPTION
**Pull request by husky-koglhof**
Tested on Mac OSX Catalina with Visual Studio Code 1.42.0 and SDL Version 2.0.10

### CODE REVIEW

**Comment by puzrin** [comment]
I don't like solution with `-D APPLE_SDL`. IMO that breaks advantages of PIO - cross platform work. It looks like `driver.c` patches should be part of `lv_drivers`. Let me know what do you think.

**Comment by husky-koglhof** [comment]
Hi, no Problem, this is a "simple and stupid" workaround for that.
I've changed it now to use following flags:
syscalls.c:
#if !defined(__APPLE__) && !defined(TARGET_OS_MAC) && BUILD_ENV_NAME == stm32f429_disco

driver.c:
#if defined(__APPLE__) && defined(TARGET_OS_MAC)
#  if __APPLE__ && TARGET_OS_MAC

**Comment by puzrin** [comment]
Let me explain my point of view. For me, "demo" is something like "good, recommended sample". Not just "something forced to run with kludges". So, it would be really great to add OSX support more clean and transparent (if technically possible).

Take a look at https://github.com/littlevgl/lv_drivers/blob/master/display/monitor.c#L112. As fas as i understand, lv_drivers already have OSX support (but poorly guarded). It seems more logical to improve flags there, instead of local patches.

About `sys/syscall.c` - it doesn't looks correct to disable IO redirect for OSX. Need comments.

**Comment by puzrin** [comment]
@husky-koglhof also, take a look at https://github.com/puzrin/dispenser & https://github.com/puzrin/reflow_micro, those have more fresh samples of PIO-dependent things.

@kisvegabor could you comment what is https://github.com/littlevgl/lv_platformio/blob/master/src/syscalls.c for? Probably, it should be removed at all.

**Comment by husky-koglhof** [comment]
OK no problem. I will incorporate my changes into lv_drivers.
stm32f429_disco is a hardware module, such as Arduino, Raspberry Pi, ...
I changed this code (syscall.c) so that I could compile the project

**Comment by husky-koglhof** [comment]
Hi, news: I can't call "refresh" at monitor.c, cause there's an issue when doing this on mac os x:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'`

So the only way i've got it compiled und running is, to have following code within driver.c "hw_loop" method:
```
#if defined(__APPLE__) && defined(TARGET_OS_MAC)
#  if __APPLE__ && TARGET_OS_MAC
        SDL_Event event;

        while(SDL_PollEvent(&event)) {
#if USE_MOUSE != 0
            mouse_handler(&event);
#endif

#if USE_KEYBOARD
            keyboard_handler(&event);
#endif

#if USE_MOUSEWHEEL != 0
            mousewheel_handler(&event);
#endif
        }
#endif
#endif

```
If it's ok for you, i will make a new PR with the relevant changes.

**Comment by puzrin** [comment]
No, it's not ok for me. I explained above why. It would be more correct to fix drivers (at least, report bug there).

**Comment by kisvegabor** [comment]
@puzrin 
> Probably, it should be removed at all.

To be honest I don't know if it's required or not. It should be tried out. 

@husky-koglhof

Please open an issue in `lv_drivers`. I have an idea for this.

**Comment by puzrin** [comment]
1. https://github.com/littlevgl/lv_platformio/commit/39d096609aba1089a9fc043e1039e5911f1823c0 Dropped orphaned `src/syscalls.c` (reduced OS-dependent places)
2. Created https://github.com/littlevgl/lv_drivers/issues/91

Closing, in vavour of https://github.com/littlevgl/lv_drivers/issues/91, this should be fixed in better way.

**Comment by puzrin** [comment]
Updated drivers to fixed ones and added instructions to readme.

@husky-koglhof let me know how it is.

**Comment by puzrin** [comment]
@husky-koglhof i've added 32-bits build support ([ref](https://forum.littlevgl.com/t/different-pool-memory-consumption-in-sim-and-bare-metal/1489/))

Could you prepare instructions for OSX 32-bits libs install?

Instructions for linux are here https://github.com/puzrin/dispenser/blob/master/doc/development.md#pc-simulator

**Pull request closed without merging**
